package com.ssm.mapper;

import com.ssm.model.BondSalesRecord;
import com.ssm.model.BondSalesRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BondSalesRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int countByExample(BondSalesRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int deleteByExample(BondSalesRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int insert(BondSalesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int insertSelective(BondSalesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    List<BondSalesRecord> selectByExample(BondSalesRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    BondSalesRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") BondSalesRecord record, @Param("example") BondSalesRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int updateByExample(@Param("record") BondSalesRecord record, @Param("example") BondSalesRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int updateByPrimaryKeySelective(BondSalesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bonds_sales_record
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    int updateByPrimaryKey(BondSalesRecord record);
}