package com.example.BondSalesManagementSystem.model;

import java.util.Date;

public class BondSalesRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonds_sales_record.id
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonds_sales_record.bonds_name
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    private String bondsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonds_sales_record.sales_name
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    private String salesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonds_sales_record.amount
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonds_sales_record.created_at
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonds_sales_record.updated_at
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonds_sales_record.id
     *
     * @return the value of bonds_sales_record.id
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonds_sales_record.id
     *
     * @param id the value for bonds_sales_record.id
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonds_sales_record.bonds_name
     *
     * @return the value of bonds_sales_record.bonds_name
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public String getBondsName() {
        return bondsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonds_sales_record.bonds_name
     *
     * @param bondsName the value for bonds_sales_record.bonds_name
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public void setBondsName(String bondsName) {
        this.bondsName = bondsName == null ? null : bondsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonds_sales_record.sales_name
     *
     * @return the value of bonds_sales_record.sales_name
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public String getSalesName() {
        return salesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonds_sales_record.sales_name
     *
     * @param salesName the value for bonds_sales_record.sales_name
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public void setSalesName(String salesName) {
        this.salesName = salesName == null ? null : salesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonds_sales_record.amount
     *
     * @return the value of bonds_sales_record.amount
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonds_sales_record.amount
     *
     * @param amount the value for bonds_sales_record.amount
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonds_sales_record.created_at
     *
     * @return the value of bonds_sales_record.created_at
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonds_sales_record.created_at
     *
     * @param createdAt the value for bonds_sales_record.created_at
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonds_sales_record.updated_at
     *
     * @return the value of bonds_sales_record.updated_at
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonds_sales_record.updated_at
     *
     * @param updatedAt the value for bonds_sales_record.updated_at
     *
     * @mbggenerated Fri Aug 20 11:26:29 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}